### ISSUE TITLE
Image might need a rebuild due to changes in Slack HTTP servers response.

### ISSUE THREAD

**Issue by lidstah** [h4110w33n/bitlbee-plugins#2]
The slack libpurple plugin has been updated 7 hours ago due to a change on the Slack HTTP servers which no longer respond to full urls:

[PR link on slack-libpurple repo](https://github.com/dylex/slack-libpurple/pull/120)

And thus Slack authentification is sadly broken with the actual docker hub image (invalid JSON response). I hope it'll help, and, btw, thank you for your work!

**Comment by h4110w33n** [comment]
Nice catch. Luckily no code changes needed for this repo. Rerolled the Docker build to incorporate the PR from `slack-libpurple`.

The `latest` tag on Dockerhub is behaving as expected for me. Closing this now, but feel free to reopen if there are any lingering issues.
